[package]
name = "dgraph"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
futures = "0.1"
grpcio = "*"
parking_lot = "0.5.3"
protobuf = "1.2"
rand = "0.4"

[build-dependencies]
protobuf = "*"
